/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TimeCapsule {
  export type MessageStruct = {
    content: string;
    unlockTime: BigNumberish;
    createdAt: BigNumberish;
  };

  export type MessageStructOutput = [
    content: string,
    unlockTime: bigint,
    createdAt: bigint
  ] & { content: string; unlockTime: bigint; createdAt: bigint };
}

export interface TimeCapsuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllMessages"
      | "getMessage"
      | "getMessageCount"
      | "getUnlockedMessages"
      | "storeMessage"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MessageStored"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllMessages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMessage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUnlockedMessages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storeMessage",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMessageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnlockedMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeMessage",
    data: BytesLike
  ): Result;
}

export namespace MessageStoredEvent {
  export type InputTuple = [
    user: AddressLike,
    messageIndex: BigNumberish,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    messageIndex: bigint,
    unlockTime: bigint
  ];
  export interface OutputObject {
    user: string;
    messageIndex: bigint;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TimeCapsule extends BaseContract {
  connect(runner?: ContractRunner | null): TimeCapsule;
  waitForDeployment(): Promise<this>;

  interface: TimeCapsuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllMessages: TypedContractMethod<
    [],
    [TimeCapsule.MessageStructOutput[]],
    "view"
  >;

  getMessage: TypedContractMethod<
    [index: BigNumberish],
    [TimeCapsule.MessageStructOutput],
    "view"
  >;

  getMessageCount: TypedContractMethod<[], [bigint], "view">;

  getUnlockedMessages: TypedContractMethod<
    [],
    [TimeCapsule.MessageStructOutput[]],
    "view"
  >;

  storeMessage: TypedContractMethod<
    [_content: string, _unlockTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllMessages"
  ): TypedContractMethod<[], [TimeCapsule.MessageStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getMessage"
  ): TypedContractMethod<
    [index: BigNumberish],
    [TimeCapsule.MessageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessageCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUnlockedMessages"
  ): TypedContractMethod<[], [TimeCapsule.MessageStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "storeMessage"
  ): TypedContractMethod<
    [_content: string, _unlockTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MessageStored"
  ): TypedContractEvent<
    MessageStoredEvent.InputTuple,
    MessageStoredEvent.OutputTuple,
    MessageStoredEvent.OutputObject
  >;

  filters: {
    "MessageStored(address,uint256,uint256)": TypedContractEvent<
      MessageStoredEvent.InputTuple,
      MessageStoredEvent.OutputTuple,
      MessageStoredEvent.OutputObject
    >;
    MessageStored: TypedContractEvent<
      MessageStoredEvent.InputTuple,
      MessageStoredEvent.OutputTuple,
      MessageStoredEvent.OutputObject
    >;
  };
}
